---
functional:
  - Создание учетной записи пользователя
  - Вход в систему с использованием учетных данных
  - Восстановление пароля
  - Добавление, редактирование и удаление контента "кода" на сайте
  - Управление списками и категориями контента
  - Комментирование контента "кода"
  - Оценка или рейтинг контента "кода"
  - Обратная связь с пользователями через форму на сайте или электронную почту. либо на самом сайте
  - Авторизация через аккаунты в социальных сетях и через почтовые аккаунты такие как vk.com, gmail.com, yandex.ru
  - Создание отчетов о поведении пользователей на сайте 
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть способен обрабатывать большое количество трафика "например, 1000 одновременных пользователей"
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров Google Chrome, Mozilla Firefox  
implicit:
  - Отслеживание статистики посещаемости сайта
  - Настройка мета-тегов для каждой страницы
  - Настройка ЧПУ (числовое программное управление) для улучшения видимости сайта в поисковых системах
