---
functional:
  - Создание учетной записи пользователя
  - Вход в систему с использованием учетных данных
  - Восстановление пароля
  - Добавление, редактирование и удаление контента "кода" на сайте
  - Управление списками и категориями контента
  - Комментирование контента "кода"
  - Оценка или рейтинг контента "кода"
  - Обратная связь с пользователями через форму на сайте или электронную почту. либо на самом сайте
  - Сайт должен быть безопасным и защищать данные пользователя
  - Прикрепление файлов "фото, видео"
  - Авторизация через аккаунты в социальных сетях
  - Отслеживание статистики посещаемости сайта
  - Создание отчетов о поведении пользователей на сайте
  - Настройка мета-тегов для каждой страницы
  - Настройка ЧПУ (человекопонятных URL) для улучшения видимости сайта в поисковых системах
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть удобным на мобильном устройстве
  - Требования к выбору кодовой базы "сделать модификацию на JavaScript, работа в репозитории клиента, использовать указанные заказчиком библиотеки при реализации модификации"
  - Сайт должен быть способен обрабатывать большое количество трафика "например, 1000 одновременных пользователей"
   
implicit:
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Нет возможности зарегестрироваться через сторонние социальные сайты
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Мало вкладок на сайте
  - Нет информации о самом сайте
